fix: release failure with non-standard directory structure
With the following project structure:

```
- package.json ( nuxt build src/my-app )
- node_modules
- src
|  - my-app
|  | - nuxt.config.js (srcDir: __dirname )
```

The release did not work:
```
error: .nuxt/dist/server: IO error for operation on .nuxt/dist/server: No such file or directory (os error 2)
```

This was due to the fact that the sentry-CLI is run with working
directory being where package.json is located while the relative
path resolved by the module was relative to the app (my-app) directory.

Fix by passing absolute path to sentry-cli so that it doesn't matter
what's the working directory when it's run.

Relevant doc: https://nuxtjs.org/api/configuration-rootdir/

Fix based on original PR by @matthiusieben - https://github.com/nuxt-community/sentry-module/pull/122

Resolves #132